FROM centos:7

RUN yum -y install gcc autoconf gcc-c++ make pcre-devel wget zlib-devel \
    && yum clean all \
    && rm -rf /var/cache/yum/*

COPY ext/nginx-1.23.2.tar.gz /usr/local/src/
COPY ext/openssl-1.0.2k.tar.gz /usr/local/src/
COPY ext/jemalloc-4.2.1.tar /usr/local/src/

RUN cd /usr/local/src && \
    tar -xvf jemalloc-4.2.1.tar &&\
    cd jemalloc-4.2.1 &&\
    ./configure --prefix=/usr/local/jemalloc && make && make install &&\
    echo /usr/local/jemalloc/lib >> /etc/ld.so.conf &&\
    ldconfig 

RUN cd /usr/local/src \
    && tar -xvf openssl-1.0.2k.tar.gz 

RUN cd /usr/local/src \
    && tar -xvf nginx-1.23.2.tar.gz \
    && cd nginx-1.23.2 \
    && ./configure --prefix=/usr/local/nginx \
        --with-http_stub_status_module \
        --with-http_ssl_module \
        --with-http_v2_module \
        --with-http_gzip_static_module \
        --with-ipv6 \
        --with-http_sub_module \
        --with-openssl=/usr/local/src/openssl-1.0.2k \
        --with-ld-opt=-Ljemalloc && make && make install

RUN mkdir /usr/local/nginx/conf/vhost
ENV PATH $PATH:/usr/local/nginx/sbin

COPY conf/nginx.conf /usr/local/nginx/conf/nginx.conf

WORKDIR /usr/local/nginx

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"] 

